market/tariff/models.py
# coding: utf-8
from __future__ import division

import logging

from copy import copy
from datetime import date, datetime
import decimal
from decimal import Decimal
from monthdelta import monthdelta, monthmod

from django.db import models
from django.db.models.signals import post_save, post_delete
from django.db import transaction
from django.conf import settings
from django.dispatch import receiver
from django.utils import timezone
from django.utils.encoding import force_text, python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as lazy_, ugettext as _
from django.utils.functional import cached_property

from invoice.models import Invoice
from dbmail import send_db_mail

from market.core.models import Vendor, Offer
from market.core.signals import vendor_open, vendor_closed
from market.utils import defaults
from market.utils.models import CurrencyField

logger = logging.getLogger(__name__)


@python_2_unicode_compatible
class Billing(models.Model):
    """One billing per vendor. It keeps track of their setting of billing app.

    This model stores which vendor has chosen which billing period and when the last billing was
    performed. The :method:`bill` is periodically called by an external tool.
    """

    PERIODS = (
        (1, lazy_('monthly')),
        (3, lazy_('quartely')),
        (6, lazy_('half-yearly')),
        (12, lazy_('yearly')),
    )
    DEFAULT_PERIOD = 3

    vendor = models.OneToOneField('market.Vendor')

    period = models.PositiveIntegerField(default=DEFAULT_PERIOD, choices=PERIODS)
    next_period = models.PositiveIntegerField(
        lazy_("Next billing period"), default=DEFAULT_PERIOD, choices=PERIODS)
    last_billed = models.DateField(default=timezone.now)
    next_billing = models.DateField(blank=True, help_text=lazy_('Is set automatically'))
    active = models.BooleanField(default=True, db_index=True)

    class Meta:
        """Meta class to force ordering by date."""
        app_label = "market"
        verbose_name = _("Billing")
        verbose_name_plural = _("Billings")

    def __str__(self):
        return _("{0.name} next billing {1:%d.%m.%Y}").format(self.vendor, self.next_billing)

    def save(self, *args, **kwargs):
        """Sync times on save."""
        if self.next_period != self.period:
            if timezone.now().date() in (self.last_billed, self.next_billing):
                self.period = self.next_period
                self.next_billing = self.last_billed + monthdelta(self.period)

        self.next_billing = self.last_billed + monthdelta(self.period)
        return super(Billing, self).save(*args, **kwargs)

    @cached_property
    def tariff(self):
        """Current tariff based of statistics of a vendor."""
        return Statistics.objects.current(self.vendor).tariff

    def close(self):
        """Close the vendor and issue last billing."""
        self.active = False
        self.next_billing = timezone.now().date()
        return self.bill()

    @transaction.atomic
    def bill(self):
        """
        Issue a bill for a vendor.

        This method is called periodically by an external tool. It let all duties bill up and the
        executes all price modifiers such as discount encounters.

        We have to bill the vendor at the time of call. Only when the billing happened already
        today (or in the future) we will ignore that call.

        :rvalue:`tariff.Bill` the created bill (invoice)
        """
        if self.last_billed >= timezone.now().date():
            return Bill.objects.filter(period_end=timezone.now().date()).get()

        if self.next_billing > timezone.now().date():
            raise ValueError("Can not bill before the end of billing period - close it instead.")

        contractor = defaults.vendor()
        bill = Bill.objects.create(
            vendor=self.vendor, logo=contractor.logo.path if contractor.logo else None,
            subscriber=self.vendor.address,
            period_start=self.last_billed, period_end=self.next_billing,
            contractor=contractor.address, contractor_bank=contractor.bank_account)

        months, rest = monthmod(self.last_billed, self.next_billing)
        # tranform date to datetime for billing useng StatisticsManager
        last_billed = datetime(self.last_billed.year, self.last_billed.month, self.last_billed.day)
        # bill by months (because of Discounts and better visibility on the bill)
        for month in range(months.months):
            total = Decimal("0.00")
            for tariff, price in Statistics.objects.bill(self.vendor,
                                                         last_billed + monthdelta(month),
                                                         last_billed + monthdelta(month + 1)):
                bill.add_item(tariff, price, settings.TAX)
                total += price

            discount = Discount.objects.cut_the_price(self.vendor, total)
            if discount is not None:
                bill.add_item(*discount)

        # bill the remaining time (if there is some)
        if rest.days > 1:
            total = Decimal("0.00")
            for tariff, price in Statistics.objects.bill(self.vendor,
                                                         last_billed + months,
                                                         last_billed + months + rest):
                bill.add_item(tariff, price, settings.TAX)
                total += price

            discount = Discount.objects.cut_the_price(self.vendor, total)
            if discount is not None:
                bill.add_item(*discount)

        if bill.total < 0:
            bill.add_item(_("Rounding price to zero"), -1 * bill.total)

        self.last_billed = self.next_billing

        self.save()  # periods change is taken care of in .save() method
        bill.save()
        bill.send()
        return bill


@python_2_unicode_compatible
class Tariff(models.Model):
    """Tarrif assigned to every vendor and reviewed with every change in amount of products."""

    name = models.CharField(max_length=120)
    description = models.TextField(null=True)
    slug = models.SlugField()
    daily = CurrencyField(default=0)
    active = models.BooleanField(db_index=True, default=True)
    # following fields set limits when the tariff should be used
    quantity = models.IntegerField()
    price = CurrencyField()

    class Meta:
        """Meta class to force ordering by date."""
        app_label = "market"
        verbose_name = _("Tariff")
        verbose_name_plural = _("Tariffs")
        ordering = ("daily", )

    def __str__(self):
        return self.name

    def total(self, days, end=None):
        """Return price for the tariff wrt days of usage or dates of usage."""
        if end is not None and isinstance(days, (date, datetime)):
            days = (end - days).days
        return (self.daily * Decimal(days)).to_integral_value(rounding=decimal.ROUND_HALF_UP)

    @property
    def monthly(self):
        """Return the monthly price for this tariff."""
        return (self.daily * Decimal("30")).to_integral_value(rounding=decimal.ROUND_HALF_UP)


class StatisticsManager(models.Manager):
    """Hold stats for a vendor.

    This class is used to decide for tariff assignments.
    """

    def create(self, vendor, save=True, **kwargs):
        """Precompute stats upon creation of new stats."""
        stat = Statistics(vendor=vendor)
        qs = vendor.offer_set.filter(active=True).exclude(quantity=0)
        stat.quantity = qs.count()
        stat.price = qs.aggregate(models.Sum('unit_price'))['unit_price__sum'] or Decimal(0)
        stat.tariff = Tariff.objects.filter(
            active=True, quantity__gte=stat.quantity, price__gte=stat.price).order_by("daily")[0]
        if save:
            stat.save(using=self._db)
        return stat

    def current(self, vendor):
        """Return the most recent stats (since we keep historical records)."""
        return self.get_queryset().filter(vendor=vendor).latest("created")

    def bill(self, vendor, period_start, period_end):
        """Use statistics records to select propriate tariffs.

        :return: list of tuples(<text>, price) ready to be added to a bill
        """
        prime = self.get_queryset().filter(vendor=vendor,
                                           created__lte=period_start
                                           ).latest("created")
        following = self.get_queryset().filter(vendor=vendor,
                                               created__gt=period_start,
                                               created__lte=period_end
                                               ).order_by("created")
        monthly = 0
        if following.count() == 0:
            # there was no change in Offers during the whole billing period
            monthly = prime.tariff.total(period_start, period_end)
            return [(prime.to_string(period_start, period_end), monthly)]  # price

        bill_items = []
        # we have more stats during the billing period - construct chain of changes
        periods = [(period_start, prime), ]
        prev_stat = prime
        for stat in following:
            if stat.tariff == prev_stat.tariff:
                prev_stat = stat
                continue
            if stat.created.date() == prev_stat.created.date():
                prev_stat = stat
                continue
            periods.append((stat.created, stat))
        periods.append((period_end, None))
        # account tarrifs with period longer than 1 day
        for i in range(len(periods) - 1):
            start, stat = periods[i]
            end, _ = periods[i + 1]
            if (end - start).days < 1:
                continue  # ignore period shorter than 1 day
            monthly += stat.tariff.total(start, end)
            bill_items.append((stat.to_string(start, end), stat.tariff.total(start, end)))
        return bill_items

market/tariff/templates/market/tariff/tariff-list.html
{% extends "neutral.html" %}
{% load core_tags %}

{% block head-title%}{% trans "Pricing" %}{%endblock%}

{% block backlinks %}
    <li> <a href="{{ request.get_full_url }}">{% trans "Pricing" %}</a> </li>
{% endblock backlinks %}

{% block content %}

    <table class="table table-hover">
        <thead>
            <tr>
                <th>{% trans "Tariff" %}</th>
                <th>{% trans "Monthly" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
                <tr>
                    <td>{{ object.name }} {{ object.description }}</td>
                    <td>{{ object.monthly }} {% trans "$" %}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

market/tariff/templates/market/tariff/tariff-manage.html
{% extends "private.html" %}
{% load core_tags fields %}

{% block head-title%}{% trans "Billing management" %}{%endblock%}

{% block content %}
    <div class="row">
        <div class="col-xs-12 col-md-6 no-left-padding">
            <div class="content-unit">
                <h1>{% trans "Tariffs" %}</h2>
                <strong>{% trans "Current tariffs" %}</strong>
                <p>
                    {{ billing.tariff.name }}
                </p>
                <strong>{% trans "Current billing period" %}</strong>
                <p>
                    {{ billing.get_period_display }}
                </p>
                <form method="post" class="form">
                    {% field form.next_period %}
                    <p>
                    {% if billing.last_billed == today %}
                    {% trans "We are changing your billing period today" %}
                    {% else %}
                    {% trans "We will change your billing period in" %} {{billing.next_billing|timeuntil}}.
                    {% endif %}
                    </p><br>
                    <input type="submit" name="tariff" class="btn btn-success btn-submit" value="{% trans "Change billing period" %}"/>
                    {% csrf_token %}
                </form>
            </div>
        </div>

        <div class="col-xs-12 col-md-6 no-right-padding">
            {% if campaign_active %}
            <div class="content-unit">
                <h2>{% trans "Discount coupon?" %}</h2>
                <form method="post" class="form">
                    {% csrf_token %}
                    {% hfield campaign_form.code %}
                    <input type="submit" name="campaign" value="{% trans "Spin it!" %}" class="btn btn-success btn-submit">
                </form>
            </div>
            {% endif %}

            {% if discounts %}
            <div class="content-unit">
                <h2>{% trans "You were discounted" %}</h2>
                <ul class="nolist">
                {% for discount in discounts %}
                    <li><strong>{{discount.name}}</strong><br>
                        <span class="subline">{{discount}}</span>
                    </li>
                {% endfor %}
                </ul>
            </div>
            {% endif %}

            <div class="content-unit">
                <h2>{% trans "Invoices" %}</h2>
                {% for bill in bills %}
                    {% if bill.proforma.paid %}
                        <a href="{% url 'invoice' uid=bill.invoice.uid %}"> {{ bill.invoice }} </a>
                    {% else %}
                        <a href="{% url 'invoice' uid=bill.proforma.uid %}"> {{ bill.proforma }} </a>
                    {% endif %}
                {% empty %}
                    {% trans "No invoices yet" %}
                {% endfor %}
            </div>
        </div>

    </div>
{% endblock content %}